FROM nginxinc/nginx-unprivileged:1.23.2

COPY /etesync-web/build /usr/share/nginx/html/client
COPY /etesync-notes/web-build /usr/share/nginx/html/notes
COPY context/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 8080



