---
name: Github Build and Push

on: 
  workflow_dispatch:
    inputs:
      platforms:
        description: 'Set the platforms to build [ linux/amd64, linux/arm64 or linux/arm/v7 ]'
        required: false
        default: 'linux/amd64,linux/arm64,linux/arm/v7'
      pushit:
        description: 'Should push?'
        required: false
        default: 'false'

jobs:
  action-stable-build:
    runs-on: ubuntu-latest
    env:
      # renovate: datasource=github-tags depName=etesync/etesync-web
      CLIENT_VERSION: v0.6.1
      # renovate: datasource=github-tags depName=etesync/etesync-notes
      NOTES_VERSION: v1.7.0
    steps:
      - name: Checkout Dockerfiles and Context
        uses: actions/checkout@v3.6.0

      - name: Checkout Etesync Web Client
        uses: actions/checkout@v3
        with:
          repository: etesync/etesync-web.git
          path: etesync-web
          ref: ${{ env.CLIENT_VERSION }}

      - name: Checkout Etesync Notes
        uses: actions/checkout@v3
        with:
          repository: etesync/etesync-notes.git
          path: etesync-notes
          ref: ${{ env.NOTES_VERSION }}
      
      - uses: actions/setup-node@v3
        with:
          node-version: '17'
          cache: 'yarn'
          cache-dependency-path: '**/yarn.lock'
      
      - run: |
          yarn global add expo-cli;
          export NODE_OPTIONS=--openssl-legacy-provider;
          cd "$GITHUB_WORKSPACE"/etesync-web;
          yarn install;
          yarn build;
          cd "$GITHUB_WORKSPACE"/etesync-notes;
          yarn;
          expo build:web

      - id: gen-tag
        shell: bash
        run: |
          TAG="w${CLIENT_VERSION#v}n${NOTES_VERSION#v}"
          echo ::set-output name=tag::${TAG}

      - id: docker_metadata
        uses: docker/metadata-action@v4.6.0
        with:
          labels: |
            maintainer=victor-rds
            org.opencontainers.image.authors='Victor R. Santos <victor-rds@users.noreply.github.com>'
          images: |
            victorrds/etesync-clients
          flavor: |
            latest=true
          tags: |
            type=raw,value=${{ steps.gen-tag.outputs.tag }}

      - name: Set up QEMU
        if: contains(github.event.inputs.platforms, 'linux/arm')
        uses: docker/setup-qemu-action@v2.2.0

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2.10.0

      - name: Login to DockerHub
        if: contains(github.event.inputs.pushit, 'true')
        uses: docker/login-action@v2.2.0
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Docker Build and Push
        id: docker_build_push
        uses: docker/build-push-action@v3.3.1
        with:
          builder: ${{ steps.buildx.outputs.name }}
          platforms: ${{ github.event.inputs.platforms }}
          context: .
          file: ./Dockerfile.nginx
          build-args: |
            CLIENT_VERSION=${{ env.CLIENT_VERSION }}
            NOTES_VERSION=${{ env.NOTES_VERSION }}
          tags: ${{ steps.docker_metadata.outputs.tags }}
          labels: ${{ steps.docker_metadata.outputs.labels }}
          push: ${{ contains(github.event.inputs.pushit, 'true') }}