---
name: Build and Push

on: 
  workflow_dispatch:
    inputs:
      stable:
        description: 'Use stable versions?'
        required: true
        default: 'false'
      platforms:
        description: 'Set the platforms to build [ linux/amd64, linux/arm64 or linux/arm/v7 ]'
        required: false
        default: 'linux/amd64,linux/arm64,linux/arm/v7'
      pushit:
        description: 'Should push?'
        required: false
        default: 'false'
      only_edge:
        description: 'Push only edge tag?'
        required: false
        default: 'true'

jobs:
  dispatch-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Dockerfiles and Context
        uses: actions/checkout@v2
      
      - id: gen-versions
        env:
          STABLE: "${{ github.event.inputs.branch }}"
        shell: bash
        run: |
          source version

          declare TAG

          if [ "${{ env.JSON_INPUT }}" = "true" ]; then
            TAG="w${CLIENT_VERSION#v}n${NOTES_VERSION#v}"
          else
            CLIENT_VERSION="master"
            NOTES_VERSION="master"
            TAG="wnmaster"
          fi

          echo ::set-output name=client_version::${CLIENT_VERSION}
          echo ::set-output name=notes_version::${NOTES_VERSION}
          echo ::set-output name=tag::${TAG}

      - id: docker_metadata
        uses: docker/metadata-action@v3.6
        with:
          labels: |
            maintainer=victor-rds
            org.opencontainers.image.authors='Victor R. Santos <victor-rds@users.noreply.github.com>'
          images: |
            victorrds/etesync-clients
          flavor: |
            latest=${{ contains(github.event.inputs.only_edge, 'false') ) }}
          tags: |
            type=edge,enable=${{ contains(github.event.inputs.only_edge, 'true') }}
            type=raw,value=${{ steps.gen-versions.outputs.tag }},enable=${{ contains(github.event.inputs.only_edge, 'false') }}

      - name: Set up QEMU
        if: contains(github.event.inputs.platforms, 'linux/arm')
        uses: docker/setup-qemu-action@v1.2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1.6

      - name: Login to DockerHub
        if: contains(github.event.inputs.pushit, 'true')
        uses: docker/login-action@v1.10
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Docker Build and Push
        id: docker_build_push
        uses: docker/build-push-action@v2.7
        with:
          builder: ${{ steps.buildx.outputs.name }}
          platforms: ${{ github.event.inputs.platforms }}
          context: .
          file: ./Dockerfile
          build-args: |
            CLIENT_VERSION=${{ steps.gen-versions.outputs.client_version }}
            NOTES_VERSION=${{ steps.gen-versions.outputs.notes_version }}
          tags: ${{ steps.docker_metadata.outputs.tags }}
          labels: ${{ steps.docker_metadata.outputs.labels }}
          push: ${{ contains(github.event.inputs.pushit, 'true') }}