---
name: Master Build and Push

on: 
  workflow_dispatch:
    inputs:
      platforms:
        description: 'Set the platforms to build [ linux/amd64, linux/arm64 or linux/arm/v7 ]'
        required: false
        default: 'linux/amd64,linux/arm64,linux/arm/v7'
      pushit:
        description: 'Should push?'
        required: false
        default: 'false'

jobs:
  dispatch-master-build:
    runs-on: ubuntu-latest   
    steps:
      - name: Checkout Dockerfiles and Context
        uses: actions/checkout@v3.0.1

      - id: docker_metadata
        uses: docker/metadata-action@v3.7.0
        with:
          labels: |
            maintainer=victor-rds
            org.opencontainers.image.authors='Victor R. Santos <victor-rds@users.noreply.github.com>'
          images: |
            victorrds/etesync-clients
          flavor: |
            latest=false
          tags: |
            type=edge,enable=true

      - name: Set up QEMU
        if: contains(github.event.inputs.platforms, 'linux/arm')
        uses: docker/setup-qemu-action@v1.2.0

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1.6.0

      - name: Login to DockerHub
        if: contains(github.event.inputs.pushit, 'true')
        uses: docker/login-action@v1.14.1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Docker Build and Push
        id: docker_build_push
        uses: docker/build-push-action@v2.10.0
        with:
          builder: ${{ steps.buildx.outputs.name }}
          platforms: ${{ github.event.inputs.platforms }}
          context: .
          file: ./Dockerfile
          tags: ${{ steps.docker_metadata.outputs.tags }}
          labels: ${{ steps.docker_metadata.outputs.labels }}
          push: ${{ contains(github.event.inputs.pushit, 'true') }}